# Generated by Django 3.2.15 on 2022-10-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.JSONField(default=list),
        ),
    ]
