name: Create Cluster

on:
  - pull_request
  - push

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0

      - name: Check dir
        run: ls helm/oncall

      - name: Check kubectl
        run: kubectl get pods

      - name: Run test suite
        run: helm install test-release helm/oncall --values helm/ci/simple.yml

      - name: Await jupyterhub
        uses: jupyterhub/action-k8s-await-workloads@v1
        with:
          workloads: "" # all
          namespace: "" # default
          timeout: 60
          max-restarts: 0

      - name: Check kubectl
        run: kubectl get pods